---

- name: ensure ssl directory exists
  ansible.builtin.file:
    path: /etc/apache2/sslcerts
    state: directory
    mode: '0755'
    owner: 'root'

- name: create a new key
  ansible.builtin.shell:
    cmd: openssl req -new -newkey rsa:2048 -nodes -keyout {{ ansible_facts['fqdn'] }}.key -out {{ ansible_facts['fqdn'] }}.csr -subj "/C=US/ST=CA/L=Alameda/O=Wind River systems, Inc./CN={{ ansible_facts['fqdn'] }}" -addext "subjectAltName=DNS:{{ ansible_facts['hostname'] }}.wrs.com,DNS:{{ ansible_facts['hostname'] }},DNS:{{ ansible_facts['hostname'] }}.corp.ad.wrs.com,DNS:{{ ansible_facts['hostname'] }}.idm.wrs.com"
    chdir: /etc/apache2/sslcerts
    creates: "{{ ansible_facts['fqdn'] }}.key"

- name: self sign the cert
  ansible.builtin.shell:
    cmd: openssl x509 -req -in {{ ansible_facts['fqdn'] }}.csr -signkey {{ ansible_facts['fqdn'] }}.key -out {{ ansible_facts['fqdn'] }}.crt -days 365
    chdir: /etc/apache2/sslcerts
    creates: "{{ ansible_facts['fqdn'] }}.crt"
